### ISSUE TITLE
Do we need the elipsis? 

### ISSUE THREAD

**Issue by adam-bro** [shad-k/loopring-explorer#4]
<img width="686" alt="Screen Shot 2022-03-28 at 7 13 47 PM" src="https://user-images.githubusercontent.com/84410897/160502439-4303281a-d553-4018-b223-4790a292e07e.png">

**Comment by adam-bro** [comment]
and also this - https://github.com/Loopring/loopring-wallet-feedback/issues/187

**Comment by shad-k** [comment]
This issue is no longer relevant as we have now switched to next/previous button type pagination.
