### ISSUE TITLE
Open new link in tab

### ISSUE THREAD

**Issue by adam-bro** [shad-k/loopring-explorer#5]
<img width="698" alt="Screen Shot 2022-03-28 at 8 18 45 PM" src="https://user-images.githubusercontent.com/84410897/160508135-02db37ad-2cde-414b-a313-a6b2c3cc25a2.png">

https://discord.com/channels/488848270525857792/948817040716738601/953651595407671307

**Comment by shad-k** [comment]
The requirement here is to make the logo act like a link rather than programmatically taking the user to the home page.
This is fixed in https://github.com/Loopring/loopring-explorer/pull/28
